repos:
  - repo: local
    hooks:
      - id: clean-notebooks
        name: Clean Jupyter notebooks
        entry: python scripts/clean_staged_notebooks.py
        language: system
        files: "\\.ipynb$"
