name: tractorcare
description: Predictive Maintenance Platform for Tractors in Rwanda

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0

  # State Management
  provider: ^6.1.1

  # HTTP Requests
  http: ^1.1.0

  # Audio Recording
  record: ^5.0.4
  permission_handler: ^11.0.1
  path_provider: ^2.1.1

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # Date/Time
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add assets here when you have images
  assets:
    - assets/images/tractorcare_logo.png